# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Nginx Ansible role.
#
# The Webarchitects Nginx Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Nginx Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Nginx Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Nginx checks
  block:

    - name: Check that legacy variables are not defined
      ansible.builtin.assert:
        that:
          - nginx_tls1_1 is not defined
          - nginx_tls1_3 is not defined
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Stat /etc/nginx
      ansible.builtin.stat:
        path: /etc/nginx
      register: nginx_etc

    - name: Set a variable to incidate that IPv6 is enabled
      ansible.builtin.set_fact:
        nginx_ipv6: true
      when: ansible_default_ipv6 | length > 0

    - name: Check TLS certificates
      block:

        - name: Check the cert
          ansible.builtin.stat:
            path: "{{ nginx_default_ssl_certificate }}"
          register: nginx_cert

        - name: Check the key
          ansible.builtin.stat:
            path: "{{ nginx_default_ssl_certificate_key }}"
          register: nginx_key

        - name: Check the CA
          ansible.builtin.stat:
            path: "{{ nginx_default_ssl_trusted_certificate }}"
          register: nginx_ca

        - name: Check the cert info
          block:

            - name: Read TLS cert information
              community.crypto.x509_certificate_info:
                path: "{{ nginx_default_ssl_certificate }}"
                valid_at:
                  tomorrow: "+1d"
                  next_week: "+1w"
                  next_month: "+1m"
              register: nginx_cert_info

            - name: Debug cert info
              ansible.builtin.debug:
                var: synapse_cert_info
                verbosity: 3

            - name: Set a fact to enable TLS for the default server
              ansible.builtin.set_fact:
                nginx_default_tls: true
              when:
                - nginx_cert_info.subject.commonName == nginx_default_server_name
                - nginx_cert_info.valid_at.next_week | bool

          when:
            - nginx_cert.stat.exists | bool
            - nginx_key.stat.exists | bool
            - nginx_ca.stat.exists | bool

      when:
        - nginx_default_ssl_certificate is defined
        - nginx_default_ssl_certificate | length > 0
        - nginx_default_ssl_certificate_key is defined
        - nginx_default_ssl_certificate_key | length > 0
        - nginx_default_ssl_trusted_certificate is defined
        - nginx_default_ssl_trusted_certificate | length > 0

  tags:
    - nginx
    - ngnix_config
...
