# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Nginx Ansible role.
#
# The Webarchitects Nginx Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Nginx Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Nginx Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Nginx checks
  block:

    - name: Check that legacy variables are not defined
      ansible.builtin.assert:
        that:
          - nginx_tls1_1 is not defined
          - nginx_tls1_3 is not defined
        quiet: "{% if ansible_verbosity == 0 %}true{% else %}false{% endif %}"

    - name: Stat /etc/nginx
      ansible.builtin.stat:
        path: /etc/nginx
      register: nginx_etc

    - name: Set a variable to incidate that IPv6 is enabled
      ansible.builtin.set_fact:
        nginx_ipv6: true
      when: ansible_default_ipv6 | length > 0

  tags:
    - nginx
    - ngnix_config
...
