---
- name: Nginx package present
  apt:
    pkg: nginx-full
    state: latest
    update_cache: yes
  tags:
    - nginx

- name: Nginx Default sites-available updated
  copy:
    src: files/default
    dest: /etc/nginx/sites-available/default
  register: nginx_sites_available_default
  tags:
    - nginx

- name: Nginx restarted
  service:
    name: nginx
    state: restarted
  when: nginx_sites_available_default.changed
  tags:
    - nginx
