---
- name: Nginx package present
  apt:
    pkg: nginx-full
    state: latest
    update_cache: yes
  tags:
    - nginx

- name: Nginx Default sites-available updated
  copy:
    src: files/default
    dest: /etc/nginx/sites-available/default
  register: nginx_sites_available_default
  tags:
    - nginx

- name: Nginx localhost conf in place
  template:
    src: templates/localhost.conf.j2
    dest: /etc/nginx/sites-available/localhost.conf

- name: Nginx localhost enabled
  file:
    path: /etc/nginx/sites-enabled/localhost.conf
    src: /etc/nginx/sites-available/localhost.conf
    state: link

- name: Nginx restarted
  service:
    name: nginx
    state: restarted
  when: nginx_sites_available_default.changed
  tags:
    - nginx
...
