---
- name: Nginx package present
  apt:
    pkg: nginx-extras
    state: present
    update_cache: false
  tags:
    - nginx

- name: Generate DH Parameters
  openssl_dhparam:
    path: /etc/nginx/ssl_dhparam.pem
    size: 2048
  tags:
    - nginx

- name: Nginx conf in place
  template:
    name: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  register: nginx_conf
  tags:
    - nginx

- name: Nginx Default sites-available updated
  copy:
    src: files/default
    dest: /etc/nginx/sites-available/default
  register: nginx_sites_available_default
  tags:
    - nginx

- name: Nginx localhost conf in place
  template:
    src: templates/localhost.conf.j2
    dest: /etc/nginx/sites-available/localhost.conf
  tags:
    - nginx

- name: Nginx localhost enabled
  file:
    path: /etc/nginx/sites-enabled/localhost.conf
    src: /etc/nginx/sites-available/localhost.conf
    state: link
  tags:
    - nginx

- name: Nginx restarted
  service:
    name: nginx
    state: restarted
  when: nginx_conf.changed or nginx_sites_available_default.changed
  tags:
    - nginx
...
