---
- name: Install nginx-extras and do some basic configuration
  block:

    - name: Nginx package present
      ansible.builtin.apt:
        pkg: "{{ nginx_packages }}"
        state: present
        update_cache: false

    - name: Generate DH Parameters
      community.crypto.openssl_dhparam:
        path: "{{ nginx_dhparam_path | default('/etc/nginx/ssl_dhparam.pem') }}"
        size: "{{ nginx_dhparam_size | default('4096') }}"
        owner: root
        group: root
        mode: 0600
      notify: Restart nginx

    - name: Set a variable to incidate that IPv6 is enabled
      ansible.builtin.set_fact:
        nginx_ipv6: true
      when: ansible_default_ipv6 | length > 0

    - name: Nginx conf in place
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart nginx

    - name: Nginx default.conf sites-available present
      ansible.builtin.template:
        src: default.conf.j2
        dest: /etc/nginx/sites-available/default.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart nginx

    - name: Nginx localhost.conf sites-available present
      ansible.builtin.template:
        src: localhost.conf.j2
        dest: /etc/nginx/sites-available/localhost.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart nginx

    - name: Check sites-enabled and sites-disabled
      block:

        - name: Check that no sites are set to be enabled and disabled at the same time
          ansible.builtin.assert:
            that:
              - nginx_sites_disabled | intersect(nginx_sites_enabled) | length == 0

      rescue:

        - name: Debug nginx_sites_disabled
          ansible.builtin.debug:
            var: nginx_sites_disabled

        - name: Debug nginx_sites_enabled
          ansible.builtin.debug:
            var: nginx_sites_enabled

         - name: Fail due to one or more sites being set to be enabled and disabled at the same time
           ansible.builtin.fail:

    - name: Nginx sites-disabled
      ansible.builtin.file:
        path: "{{ file }}"
        state: absent
      loop: "{{ nginx_sites_disabled }}"
      loop_control:
        loop_var: file
      when:
        - nginx_sites_disabled is defined
        - nginx_sites_disabled | length > 0
      notify: Restart nginx

    - name: Nginx sites-enabled
      ansible.builtin.file:
        path: "/etc/nginx/sites-enabled/{{ file }}"
        src: "/etc/nginx/sites-available/{{ file }}"
        state: link
        follow: false
        mode: 0777
        owner: root
        group: root
      loop: "{{ nginx_sites_enabled }}"
      loop_control:
        loop_var: file
      when:
        - nginx_sites_enabled is defined
        - nginx_sites_enabled | length > 0
      notify: Restart nginx

    - name: Test Nginx configuration
      ansible.builtin.command: service nginx configtest
      changed_when: false
      check_mode: false

  when: (nginx is defined) and (nginx | bool)
  tags:
    - nginx
...
