---
- name: Install nginx-extras and do some basic configuration
  block:

    - name: Nginx package present
      apt:
        pkg: "{{ pkg }}"
        state: present
        update_cache: false
      loop: "{{ nginx_packages }}"
      loop_control:
        loop_var: pkg

    - name: Generate DH Parameters
      openssl_dhparam:
        path: "{{ nginx_dhparam_path | default('/etc/nginx/ssl_dhparam.pem') }}"
        size: "{{ nginx_dhparam_size | default('4096') }}"
        owner: root
        group: root
        mode: 0600
      notify: Restart nginx

    - name: Set a variable to incidate that IPv6 is enabled
      set_fact:
        nginx_ipv6: true
      when: ansible_default_ipv6 | length > 0

    - name: Nginx conf in place
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart nginx

    - name: Nginx default sites-enabled absent
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart nginx

    - name: Nginx default.conf sites-available present
      template:
        src: default.conf.j2
        dest: /etc/nginx/sites-available/default.conf
      notify: Restart nginx

    - name: Nginx default.conf sites-enabled present
      file:
        path: /etc/nginx/sites-enabled/default.conf
        src: /etc/nginx/sites-available/default.conf
        state: link
      notify: Restart nginx

    - name: Nginx localhost conf in place
      template:
        src: localhost.conf.j2
        dest: /etc/nginx/sites-available/localhost.conf
      notify: Restart nginx

    - name: Test Nginx configuration
      command: service nginx configtest

    - name: Nginx localhost enabled
      file:
        path: /etc/nginx/sites-enabled/localhost.conf
        src: /etc/nginx/sites-available/localhost.conf
        state: link
      notify: Restart nginx

  tags:
    - nginx
...
