# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Nginx Ansible role.
#
# The Webarchitects Nginx Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Nginx Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Nginx Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skip the tasks in this role
  ansible.builtin.debug:
    msg: "The Nginx role tasks are not being run since the nginx variable is false."
  when: not nginx | bool
  tags:
    - nginx

- name: Install and configure Nginx
  block:

    - name: Validate Nginx variables
      ansible.builtin.include_tasks: validate.yml
      when: nginx_validate | bool

    - name: Nginx package present
      ansible.builtin.apt:
        pkg: "{{ nginx_packages }}"
        state: present
        update_cache: false
      notify: Restart nginx
      when:
        - nginx_packages is defined
        - nginx_packages != []
      tags:
        - nginx_install

    - name: Include checks
      ansible.builtin.include_tasks: checks.yml
      tags:
        - ngnix_config

    - name: Configure Nginx when /etc/nginx exists
      block:

        - name: DH parameter tasks
          block:

            - name: DH parameters for TLS to be generated
              ansible.builtin.debug:
                msg: "The next task, generating the DH Parameters for TLS might take some time."

            - name: Generate DH Parameters for TLS
              community.crypto.openssl_dhparam:
                path: "{{ nginx_dhparam_path }}"
                size: "{{ nginx_dhparam_size }}"
                owner: root
                group: root
                mode: "0600"
              notify: Restart nginx

          when:
            - nginx_ssl is defined
            - nginx_ssl | bool

        - name: Nginx conf in place
          ansible.builtin.template:
            src: nginx.conf.j2
            dest: /etc/nginx/nginx.conf
            owner: root
            group: root
            mode: "0644"
          notify: Restart nginx

        - name: Nginx default.conf sites-available present
          ansible.builtin.template:
            src: default.conf.j2
            dest: /etc/nginx/sites-available/default.conf
            owner: root
            group: root
            mode: "0644"
          notify: Restart nginx

        - name: Nginx localhost.conf sites-available present
          ansible.builtin.template:
            src: localhost.conf.j2
            dest: /etc/nginx/sites-available/localhost.conf
            owner: root
            group: root
            mode: "0644"
          notify: Restart nginx

        - name: Include site checks
          ansible.builtin.include_tasks: site_checks.yml

        - name: Include include site disabled tasks
          ansible.builtin.include_tasks: site_disabled.yml
          loop: "{{ nginx_sites_disabled }}"
          loop_control:
            loop_var: nginx_site
          when:
            - nginx_sites_disabled is defined
            - nginx_sites_disabled != []
            - nginx_site in nginx_existing_sites_enabled_filenames

        - name: Include site enabled tasks
          ansible.builtin.include_tasks: site_enabled.yml
          loop: "{{ nginx_sites_enabled }}"
          loop_control:
            loop_var: nginx_site
          when:
            - nginx_sites_enabled is defined
            - nginx_sites_enabled != []
            - nginx_site not in nginx_existing_sites_enabled_filenames

      when: nginx_etc.stat.exists | bool
      tags:
        - ngnix_config

  when:
    - nginx is defined
    - nginx | bool
  tags:
    - nginx
...
