# Copyright 2018-2024 Chris Croome
#
# This file is part of the Webarchitects Nginx Ansible role.
#
# The Webarchitects Nginx Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Nginx Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Nginx Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Disable site
  block:

    - name: Debug nginx_existing_sites_available
      ansible.builtin.debug:
        var: nginx_existing_sites_available_filenames
        verbosity: "{% if ansible_check_mode | bool %}0{% else %}1{% endif %}"

    - name: Fail if a site that doesn't exist is to be disabled
      ansible.builtin.fail:
        msg: "There is not point in trying to remove a symlink that points to /etc/nginx/sites-available/{{ nginx_site }} when the file doesn't exist."
      when: nginx_site not in nginx_existing_sites_available_filenames

    - name: Nginx site disabled
      ansible.builtin.file:
        path: "/etc/nginx/sites-enabled/{{ nginx_site }}"
        state: absent
      notify: Restart nginx
      when: nginx_site in nginx_existing_sites_available_filenames

  tags:
    - nginx
    - ngnix_config
...
