# Copyright 2018-2023 Chris Croome
#
# This file is part of the Webarchitects Nginx Ansible role.
#
# The Webarchitects Nginx Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Nginx Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Nginx Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Verify as root
  # become: true
  connection: local
  # gather_facts: true
  hosts:
    - localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
      register: molecule_port_facts

    - name: Debug Nginx listening ports
      ansible.builtin.debug:
        var: molecule_port_facts

    - name: Gather service facts
      ansible.builtin.service_facts:
      register: molecule_service_facts

    - name: Debug Nginx service status
      ansible.builtin.debug:
        msg: "{{ molecule_service_facts | community.general.json_query(molecule_service_jpq) }}"
        verbosity: 3
      vars:
        molecule_service_jpq: 'ansible_facts.services.["nginx.service"]|[0]'

    - name: Check that Nginx is enabled and running
      ansible.builtin.assert:
        that:
          - (molecule_service_facts | community.general.json_query(molecule_service_jpq)).status == "enabled"
          - (molecule_service_facts | community.general.json_query(molecule_service_jpq)).state == "running"
        quiet: true
      vars:
        molecule_service_jpq: 'ansible_facts.services.["nginx.service"]|[0]'

    - name: Write text to test file
      ansible.builtin.lineinfile:
        path: /var/www/html/.well-known/acme-challenge/hello_world.txt
        line: "Hello World!"
        state: present
        create: true
        owner: root
        group: root
        mode: "0644"

    - name: Check test file
      ansible.builtin.uri:
        url: "http://{{ ansible_default_ipv4.address }}:80/.well-known/acme-challenge/hello_world.txt"
        return_content: true
        status_code:
          - 200
      register: molecule_http_request

    - name: Debug the test file content
      ansible.builtin.debug:
        var: molecule_http_request.content
      when: molecule_http_request.content is defined
...
